### ISSUE TITLE
make issues

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/queuey#1]
Looks like casandra was upped to 1.0.1 yesterday, and 1.0.0 was removed.
- please add -L to the curl commands (to follow remote redirects and 302s)
- please trap for curl return status of 22 (fetch error)
- please use a major mirror for software pulls (e.g. columbia.edu) or using a managed redirect to the latest available distro.

**Comment by bbangert** [comment]
Sometimes they update the syntax of some of the config, so I don't want to blindly fetch the latest version. I'm using the permanent archive versions from apache.org instead to ensure its always available and using a known working version now.
